%% Check fluorescenceSignal against Figure 5-9 style reconstruction
%
% Goal:
% Compare the spectrum generated by fluorescenceSignal to the spectrum
% generated by the Figure 5-9 fitting model path:
%   predicted = finalFluorophores * weights
% where finalFluorophores is built from savedFluorophores with blood applied
% to collagen (column 1).
%
% Example parameter set provided by user/colleague:
% Blood log10(od) = 1.00
% Weights = [Collagen, FAD, Porphyrin, Chlorophyll-a, Keratin] =
%           [8.69, 0.55, 0.42, 0.04, 0.32]

ieInit;

wave = 500:700;
normWave = 520;

bloodLog10OD = 1.00;
odBlood = bloodLog10OD;
weights = [8.69; 0.55; 0.42; 0.04; 0.32];

%% Load saved fluorophores used by oeFigure5_9 flow
saveFile = fullfile(oeTongueLipRootPath,'data','savedFluorophores.mat');
if ~exist(saveFile,'file')
    error('Could not find %s',saveFile);
end

S = load(saveFile);

savedFluorophores = [];
selectedName = '';

preferredNames = {'savedFluorophores','finalFluorophores','fluorophores'};
for ii = 1:numel(preferredNames)
    thisName = preferredNames{ii};
    if isfield(S,thisName)
        thisVal = S.(thisName);
        if isnumeric(thisVal) && ismatrix(thisVal) && min(size(thisVal)) > 1
            savedFluorophores = thisVal;
            selectedName = thisName;
            break;
        end
    end
end

if isempty(savedFluorophores)
    fNames = fieldnames(S);
    for ii = 1:numel(fNames)
        thisName = fNames{ii};
        thisVal = S.(thisName);
        if isnumeric(thisVal) && ismatrix(thisVal) && min(size(thisVal)) > 1
            if size(thisVal,1) == numel(wave) || size(thisVal,2) == numel(wave)
                savedFluorophores = thisVal;
                selectedName = thisName;
                break;
            end
        end
    end
end

if isempty(savedFluorophores)
    error('Could not identify fluorophore basis matrix in %s.',saveFile);
end

if size(savedFluorophores,1) ~= numel(wave) && size(savedFluorophores,2) == numel(wave)
    savedFluorophores = savedFluorophores';
end

fprintf('Using variable ''%s'' from savedFluorophores.mat\n', selectedName);

if size(savedFluorophores,1) ~= numel(wave)
    error('savedFluorophores row count (%d) does not match wave length (%d).', ...
        size(savedFluorophores,1), numel(wave));
end

if size(savedFluorophores,2) < numel(weights)
    error('savedFluorophores has %d columns, but %d weights were provided.', ...
        size(savedFluorophores,2), numel(weights));
end

%% Figure 5-9 style reconstruction path
oxyblood = medium('oxy_molarExtinctionCoefficient.mat','wave',wave);
oxyblood.opticalDensity = odBlood;
oxyTransmittance = oxyblood.transmittance;

finalFluorophores = savedFluorophores(:,1:numel(weights));
finalFluorophores(:,1) = finalFluorophores(:,1) .* oxyTransmittance;
signalFigure59Path = finalFluorophores * weights;

%% fluorescenceSignal path
signalFluorescenceSignal = fluorescenceSignal(wave,odBlood,weights);

% fluorescenceSignal path using explicit basis from savedFluorophores
signalFluorescenceSignalExplicit = fluorescenceSignal(wave,odBlood,weights, ...
    'fixedfluorophores',savedFluorophores(:,1:numel(weights)));

%% Error metrics (raw)
relErrRaw = norm(signalFigure59Path(:) - signalFluorescenceSignal(:)) / ...
    max(norm(signalFigure59Path(:)),eps);
maxAbsErrRaw = max(abs(signalFigure59Path(:) - signalFluorescenceSignal(:)));

relErrRawExplicit = norm(signalFigure59Path(:) - signalFluorescenceSignalExplicit(:)) / ...
    max(norm(signalFigure59Path(:)),eps);
maxAbsErrRawExplicit = max(abs(signalFigure59Path(:) - signalFluorescenceSignalExplicit(:)));

%% Error metrics (normalized at 520 nm)
idxNorm = find(wave == normWave,1,'first');
if isempty(idxNorm)
    error('normWave %d is not in wave vector.',normWave);
end

sigA = signalFigure59Path / signalFigure59Path(idxNorm);
sigB = signalFluorescenceSignal / signalFluorescenceSignal(idxNorm);
sigBExplicit = signalFluorescenceSignalExplicit / signalFluorescenceSignalExplicit(idxNorm);

relErrNorm = norm(sigA(:) - sigB(:)) / max(norm(sigA(:)),eps);
maxAbsErrNorm = max(abs(sigA(:) - sigB(:)));

relErrNormExplicit = norm(sigA(:) - sigBExplicit(:)) / max(norm(sigA(:)),eps);
maxAbsErrNormExplicit = max(abs(sigA(:) - sigBExplicit(:)));

fprintf('\n--- Figure5_9 consistency check ---\n');
fprintf('blood log10(od) = %.2f\n', bloodLog10OD);
fprintf('weights = [%s]\n', num2str(weights','%.3f '));
fprintf('RAW:        relErr = %.3e, maxAbsErr = %.3e\n', relErrRaw, maxAbsErrRaw);
fprintf('RAW EXPL:   relErr = %.3e, maxAbsErr = %.3e\n', relErrRawExplicit, maxAbsErrRawExplicit);
fprintf('NORM@%dnm:  relErr = %.3e, maxAbsErr = %.3e\n', normWave, relErrNorm, maxAbsErrNorm);
fprintf('NORM EXPL:  relErr = %.3e, maxAbsErr = %.3e\n', relErrNormExplicit, maxAbsErrNormExplicit);

%% Plot overlays
figH1 = ieFigure;
[~, p1] = plotRadiance(wave,[signalFigure59Path, signalFluorescenceSignal, signalFluorescenceSignalExplicit], ...
    'hdl',figH1, ...
    'title',sprintf('Raw spectra | OD=%.2f',bloodLog10OD));
set(p1(1),'Color','k','LineStyle','-','LineWidth',2);
set(p1(2),'Color','r','LineStyle','--','LineWidth',2);
set(p1(3),'Color','b','LineStyle',':','LineWidth',2);
legend('Figure5_9 path (savedFluorophores)', ...
    'fluorescenceSignal (default basis)', ...
    'fluorescenceSignal (explicit basis)', ...
    'Location','best');

figH2 = ieFigure;
[~, p2] = plotRadiance(wave,[sigA, sigB, sigBExplicit], ...
    'hdl',figH2, ...
    'title',sprintf('Normalized at %d nm | OD=%.2f',normWave,bloodLog10OD));
set(p2(1),'Color','k','LineStyle','-','LineWidth',2);
set(p2(2),'Color','r','LineStyle','--','LineWidth',2);
set(p2(3),'Color','b','LineStyle',':','LineWidth',2);
legend(sprintf('Figure5_9 path (norm @ %d nm)',normWave), ...
    'fluorescenceSignal default (norm)', ...
    'fluorescenceSignal explicit (norm)', ...
    'Location','best');

disp('Check complete. Inspect printed errors and overlays.');
